namespace: new
cluster_mode: standalone
mask:
  database_plan: true
  storage_plan: true
  ingress: true 
  registry: true
  proxy: false
  custom_tls: false
database_plan:
  name: dbtemp
  type: ephemeral
storage_plan:
  name: sptemp
  type: ephemeral
ingress:
  type: kubernetes-ingress
  enable_tls: false
  k8s_ingress:
    domain:  .nip.io
    useCustomIngressClass: true
    customIngressClass: nginx
    path: /
  service: null
registry:
  type: generic
  generic_registry:
    auth_pull_url: 
    auth_push_url: 
    registry_name: 
    enable_auth: true
    auth_user: 
    auth_password: 
    link_secret_to_service_account: true

